include "root" {
  path = find_in_parent_folders("root.hcl")
}

terraform {
  source = "${get_repo_root()}/infra/terraform/_modules/kubernetes/kong"
}

# Ensure PriorityClasses exist before deploying Kong
dependency "priority_classes" {
  config_path  = "../priority-classes"
  skip_outputs = true
}

# Consume API key generated by zama-internal-api
dependency "zama_internal_api" {
  config_path  = "../zama-internal-api"
  
  # Allow init/plan before the dependency is applied
  mock_outputs = {
    api_key = "mock-api-key"
  }
  mock_outputs_allowed_terraform_commands = ["init", "plan"]
  skip_outputs = false
}

inputs = {
  kubeconfig_path      = "~/.kube/kubeconfig-zama-local-k3d.yaml"
  # namespace          = "kong"
  # release_name       = "kong"
  values_override_file = "${get_terragrunt_dir()}/values-local.yaml"
  key_auth_key         = dependency.zama_internal_api.outputs.api_key
}
